server:
  port: 8081

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/minkiboard
    driverClassName: org.mariadb.jdbc.Driver
    username: root
    password: 663966
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true